### ISSUE TITLE
Alpha

### ISSUE THREAD

**Issue by ghost** [statnmap/pdfreport#2]
Bonjour, 

J'ai un soucis avec l'inclusion de lettres greques. En effet 
```
$(\alpha)$  ou $\beta$
```
donne () dans le pdf final. Le caractère semble pourtant bien reconnu puisque lorsque je passe la souris dessus sous Rstudio in ɑ apparait.
 Une idée d'où cela pourrait venir?

Merci

**Comment by statnmap** [comment]
Je n'ai pas de mon problème de mon côté 
![image](https://user-images.githubusercontent.com/21193866/102357536-b6488f00-3fae-11eb-90a2-a576d590d17e.png)

Le code à reproduire dans un nouveau projet RStudio
```r
# devtools::install_github("statnmap/pdfreport")
library(pdfreport)
file.copy(system.file("example/template_example.Rmd", package = "pdfreport"), 
          "test.Rmd")
file.edit("test.Rmd")
# Ajouter $(\alpha)$  ou $\beta$

prepare_for_knit(rmd.path = "test.Rmd",
                 out_format = "pdf_document2",
                 knit = TRUE, output_dir = "pdf")
```

Versions : 
- rmarkdown 2.4
- knitr 1.30
- bookdown 0.21

**Comment by ghost** [comment]
Effectivement!
En fait ayant des astérisques dans mon texte j'avais ajouté "latex_engine: xelatex" car sinon j'avais un message d'erreur lié à l'encodage. Il semble que xelatex n'aime pas trop les caractères spéciaux.... 
Cela résoud du coup un autre soucis que j'avais avec les listes de puces.
Merci!
